# The MIT License
# 
# Copyright (c) 2019 Giovanni di Dio Bruno https://gbr1.github.io
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#
global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   update_frequency: 1.0  # Global costmap doesn't need frequent updates as local costmap
   publish_frequency: 0.5
   static_map: true
   transform_tolerance: 0.5
   resolution: 0.1  # Global costmap can have lower resolution
   width: 20.0  # Adjust based on the size of your environment
   height: 20.0  # Adjust based on the size of your environment
   static_map: true
   plugins:
     - {name: static_layer, type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

static_layer:
  enabled: true

obstacle_layer:
  enabled: true
  max_obstacle_height: 0.5
  origin_z: 0.0
  z_resolution: 0.2
  z_voxels: 2
  unknown_threshold: 15
  mark_threshold: 0
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 3.0  # Larger range for global obstacle detection
  raytrace_range: 4.0  # Larger range for raytracing in global map
  publish_voxel_map: true
  observation_sources: scan
  scan:
    data_type: PointCloud2
    topic: rtabmap/cloud_obstacles
    sensor_frame: base_link
    marking: true
    clearing: true
    min_obstacle_height: 0.1
    max_obstacle_height: 0.5

inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0  # Lower than local to create smoother global paths
  inflation_radius: 1.5  # Larger inflation radius for global path planning

